apiVersion: v1
entries:
  rabbitmq:
  - appVersion: 3.7.5
    created: 2018-10-16T13:08:56.345294664Z
    description: Open source message broker software that implements the Advanced
      Message Queuing Protocol (AMQP)
    digest: 545d5435d055166786d502cf321bc903ed0302a463f8dc211a9f26a91420f723
    engine: gotpl
    home: https://www.rabbitmq.com
    icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
    keywords:
    - rabbitmq
    - message queue
    - AMQP
    maintainers:
    - email: skalmad1@us.ibm.com
      name: Sunil Kalmadka
    name: rabbitmq
    sources:
    - https://github.com/bitnami/bitnami-docker-rabbitmq
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/rabbitmq-1.1.5.tgz
    version: 1.1.5
  velocity:
  - apiVersion: v1
    created: 2018-10-16T13:08:56.351700511Z
    description: Deploys UrbanCode Velocity
    digest: 9c61eb9bdbe1c18555cba6c6c7239bd00e7102145a6770047de1abb25ff1e8ee
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v1
    created: 2018-10-16T13:08:56.350802517Z
    description: Deploys UrbanCode Velocity
    digest: 929e7ced5dca431dd9004d96669e782cd2e4594100a7b6afbefdcf6a18a6fc78
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v1
    created: 2018-10-16T13:08:56.3499551Z
    description: Deploys UrbanCode Velocity
    digest: c225d594cee68672567ad6230308240c393d61eb1835c881764c4c71e041c4fb
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    created: 2018-10-16T13:08:56.349115931Z
    description: Deploys UrbanCode Velocity
    digest: 8b5226c4b21645e518b07c1b163be3e50cb044f3ee8159b7b3787152e207f4fd
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    created: 2018-10-16T13:08:56.3483011Z
    description: Deploys UrbanCode Velocity
    digest: ad8913af6b422a743c716747e20c970810a6391cca6df4221b5ac66845372cc1
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    created: 2018-10-16T13:08:56.347428401Z
    description: Deploys UrbanCode Velocity
    digest: ffcf336feed26030db092b41bb2b0b0657f5a8f2502383832aac992318027fdc
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    created: 2018-10-16T13:08:56.346700491Z
    description: Deploys UrbanCode Velocity
    digest: e0842b25d37099579fc9ddc6629717952fb0e5490936fc454381d8abda3f06f3
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    created: 2018-10-16T13:08:56.346018642Z
    description: Deploys UrbanCode Velocity
    digest: 41efb77f46b5386585dc4cfcbb1f64214bbc88dfb5b32a6c7419ed99fbee6087
    name: velocity
    urls:
    - https://raw.githubusercontent.com/IBM/velocity-se/master/kubernetes/repo/velocity-1.0.0.tgz
    version: 1.0.0
generated: 2018-10-16T13:08:56.344427772Z
